language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
git:
  depth: 3
script:
  - yarn build

after_success:
  skip-cleanup: true
  provider: script
  script: 
    - npm install -g surge
    - ./config/travis/deploy-surge.sh