language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
git:
  depth: 3
script:
  - yarn build

after_success:
  - npm install -g surge
  - chmod +x ./config/travis/deploy-surge.sh
  - ./config/travis/deploy-surge.sh